services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-data-gpt
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - SERVER=host.docker.internal,57792
    volumes:
      - .:/app
